### ISSUE TITLE
Responsive grids

### ISSUE THREAD

**Issue by wesoudshoorn** [appsignal/design-language#33]
There's a few ways we can make our grids responsive. They are not mutually exclusive

1. Responsive grid container
1. Responsive grid children
1. Magic responsive grids

# Responsive grid container
We specify the number of columns per media query, in this way:
```css
.o-grid {
  display: grid;
  grid-gap: 1.5rem;
  grid-template-columns: repeat(4, 1fr);

  @media (min-width: 50rem) {
    grid-template-columns: repeat(8, 1fr);
  }

  @media (min-width: 75rem) {
    grid-template-columns: repeat(12, 1fr);
  }
}
```
Children with a `grid-column: span 4` would work great here, but any other numbers does not make the content flow nicely.

# Responsive grid children
We can use media queries to give children different spans on different breakpoints. A selector would look something like this:
```html
<div class="u-12/12@sm u-6/12@lg u-4/12@xl">Content</div>
```

_This would start to get very funky once you implement the first solution as well, because there'd be no 12 columns. In that case, we'd probably have to lose the `/12` and just specify the number of columns we'd like it to span._

# Automagic responsive grid
There's a great solution [this article by Rachel Andrew](https://rachelandrew.co.uk/archives/2016/04/12/flexible-sized-grids-with-auto-fill-and-minmax/) about a grid that flows nicely without media queries. 
```css
.o-grid-3-2-1 {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    grid-gap: 20px;
}
```
It basically checks how many columns of at least 300px fit, taking into account the gutters. On a 1200px grid width, that's 4. It than checks the max-width, which is 1fr. It'll create a layout of 4 even `1fr` units. 

On smaller screens, 2 or 2 columns fit. This makes it a great layout for groups of 6 items that flow from 3, to 2, to 1 column.

We can do some common setups with a few more rules to accommodate `4>2>1` layouts as well.
